/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#b4233a',
        'surface-tint': '#0f766e',
        secondary: '#1f7a4d',
        'secondary-fixed-dim': '#7ddf9b',
        'on-primary-fixed-variant': '#064e48',
        'tertiary-dim': '#1d4ed8',
        'error-dim': '#8f1329',
        'on-tertiary-fixed': '#102a58',
        'tertiary-container': '#dbeafe',
        'inverse-on-surface': '#d7dedc',
        'tertiary-fixed': '#dbeafe',
        'on-background': '#182223',
        'inverse-primary': '#7dd3c7',
        'on-primary-container': '#064e48',
        'on-error-container': '#7a1022',
        'on-tertiary': '#f8fbff',
        'surface-variant': '#d9e2df',
        'surface-bright': '#fbfdfc',
        'on-secondary-container': '#14532d',
        'surface-container-lowest': '#ffffff',
        primary: '#0f766e',
        'primary-fixed-dim': '#99f6e4',
        'outline-variant': '#c8d1ce',
        'secondary-container': '#dcfce7',
        'on-secondary-fixed': '#14532d',
        'on-tertiary-fixed-variant': '#1e40af',
        'surface-container': '#e8eeee',
        'inverse-surface': '#101819',
        'on-primary-fixed': '#063b36',
        outline: '#6a7472',
        'tertiary-fixed-dim': '#bfdbfe',
        'surface-dim': '#d9e2df',
        'on-secondary-fixed-variant': '#166534',
        'on-error': '#fff8f8',
        'primary-fixed': '#ccfbf1',
        background: '#f6f8f8',
        'surface-container-highest': '#dfe7e4',
        'on-surface': '#182223',
        'error-container': '#ffd8de',
        'surface-container-high': '#edf3f1',
        'primary-dim': '#0b5f59',
        tertiary: '#2563eb',
        'surface-container-low': '#f2f6f5',
        'on-primary': '#f8fffd',
        'on-secondary': '#f0fff4',
        'secondary-dim': '#166534',
        'primary-container': '#ccfbf1',
        surface: '#f6f8f8',
        'on-tertiary-container': '#1e3a8a',
        'secondary-fixed': '#bbf7d0',
        'on-surface-variant': '#56615f',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
